version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - AZURE_SPEECH_KEY=${AZURE_SPEECH_KEY}
      - AZURE_SPEECH_REGION=${AZURE_SPEECH_REGION}
      - SPEECH_SDK_TRACE_LOG=1
      - SPEECH_SDK_LOGGING_ENABLED=1
    restart: unless-stopped