// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.4, generator: @autorest/go@4.0.0-preview.70)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// Code generated by @autorest/go. DO NOT EDIT.

package speechclient

import "io"

// DatasetsClientCommitBlocksOptions contains the optional parameters for the DatasetsClient.CommitBlocks method.
type DatasetsClientCommitBlocksOptions struct {
	// placeholder for future optional parameters
}

// DatasetsClientCreateOptions contains the optional parameters for the DatasetsClient.Create method.
type DatasetsClientCreateOptions struct {
	// placeholder for future optional parameters
}

// DatasetsClientDeleteOptions contains the optional parameters for the DatasetsClient.Delete method.
type DatasetsClientDeleteOptions struct {
	// placeholder for future optional parameters
}

// DatasetsClientGetBlocksOptions contains the optional parameters for the DatasetsClient.GetBlocks method.
type DatasetsClientGetBlocksOptions struct {
	// placeholder for future optional parameters
}

// DatasetsClientGetFileOptions contains the optional parameters for the DatasetsClient.GetFile method.
type DatasetsClientGetFileOptions struct {
// The duration in seconds that an SAS url should be valid. The default duration is 12 hours. When using BYOS
// (https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-encryption-of-data-at-rest#bring-your-own-storage-byos-for-customization-and-logging):
// A value of 0 means that a plain
// blob URI without SAS token will be generated.
	SasValidityInSeconds *int32
}

// DatasetsClientGetOptions contains the optional parameters for the DatasetsClient.Get method.
type DatasetsClientGetOptions struct {
	// placeholder for future optional parameters
}

// DatasetsClientListFilesOptions contains the optional parameters for the DatasetsClient.NewListFilesPager method.
type DatasetsClientListFilesOptions struct {
// A filtering expression for selecting a subset of the available files. - Supported properties: name, createdDateTime, kind.
// - Operators: - eq, ne are supported for all properties. - gt, ge, lt, le are
// supported for createdDateTime. - and, or, not are supported. - Example: filter=name eq 'myaudio.wav' and kind eq 'Audio'
	Filter *string

// The duration in seconds that an SAS url should be valid. The default duration is 12 hours. When using BYOS
// (https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-encryption-of-data-at-rest#bring-your-own-storage-byos-for-customization-and-logging):
// A value of 0 means that a plain
// blob URI without SAS token will be generated.
	SasValidityInSeconds *int32

// Number of datasets that will be skipped.
	Skip *int32

// Number of datasets that will be included after skipping.
	Top *int32
}

// DatasetsClientListOptions contains the optional parameters for the DatasetsClient.NewListPager method.
type DatasetsClientListOptions struct {
// A filtering expression for selecting a subset of the available datasets. - Supported properties: displayName, description,
// createdDateTime, lastActionDateTime, status, locale, kind. - Operators: - eq,
// ne are supported for all properties. - gt, ge, lt, le are supported for createdDateTime and lastActionDateTime. - and,
// or, not are supported. -Example: filter=createdDateTime gt 2022-02-01T11:00:00Z
// and displayName eq 'My dataset'
	Filter *string

// Number of datasets that will be skipped.
	Skip *int32

// Number of datasets that will be included after skipping.
	Top *int32
}

// DatasetsClientListSupportedLocalesOptions contains the optional parameters for the DatasetsClient.ListSupportedLocales
// method.
type DatasetsClientListSupportedLocalesOptions struct {
	// placeholder for future optional parameters
}

// DatasetsClientUpdateOptions contains the optional parameters for the DatasetsClient.Update method.
type DatasetsClientUpdateOptions struct {
	// placeholder for future optional parameters
}

// DatasetsClientUploadBlockOptions contains the optional parameters for the DatasetsClient.UploadBlock method.
type DatasetsClientUploadBlockOptions struct {
	// placeholder for future optional parameters
}

// DatasetsClientUploadOptions contains the optional parameters for the DatasetsClient.Upload method.
type DatasetsClientUploadOptions struct {
// The optional custom properties of this entity. The maximum allowed key length is 64 characters, the maximum allowed value
// length is 256 characters and the count of allowed entries is 10.
	CustomProperties *string

// For acoustic datasets, a zip file containing the audio data and a text file containing the transcriptions for the audio
// data. For language datasets, a text file containing the language or
// pronunciation data. Required in both cases.
	Data io.ReadSeekCloser

// Optional description of this dataset.
	Description *string

// An optional string containing the email address to send email notifications to in case the operation completes. The value
// will be removed after successfully sending the email.
	Email *string

// The optional string representation of the url of a project. If set, the dataset will be associated with that project.
	Project *string
}

// EndpointsClientCreateOptions contains the optional parameters for the EndpointsClient.Create method.
type EndpointsClientCreateOptions struct {
	// placeholder for future optional parameters
}

// EndpointsClientDeleteBaseModelLogOptions contains the optional parameters for the EndpointsClient.DeleteBaseModelLog method.
type EndpointsClientDeleteBaseModelLogOptions struct {
	// placeholder for future optional parameters
}

// EndpointsClientDeleteBaseModelLogsOptions contains the optional parameters for the EndpointsClient.DeleteBaseModelLogs
// method.
type EndpointsClientDeleteBaseModelLogsOptions struct {
// The end date of the audio logs deletion (specific day, UTC). Expected format: "yyyy-mm-dd". For instance, "2023-03-15"
// results in deleting all logs on March 15th, 2023 and before. Deletes all existing
// logs when date is not specified.
	EndDate *string
}

// EndpointsClientDeleteLogOptions contains the optional parameters for the EndpointsClient.DeleteLog method.
type EndpointsClientDeleteLogOptions struct {
	// placeholder for future optional parameters
}

// EndpointsClientDeleteLogsOptions contains the optional parameters for the EndpointsClient.DeleteLogs method.
type EndpointsClientDeleteLogsOptions struct {
// The end date of the audio logs deletion (specific day, UTC). Expected format: "yyyy-mm-dd". For instance, "2023-03-15"
// results in deleting all logs on March 15th, 2023 and before. Deletes all existing
// logs when date is not specified.
	EndDate *string
}

// EndpointsClientDeleteOptions contains the optional parameters for the EndpointsClient.Delete method.
type EndpointsClientDeleteOptions struct {
	// placeholder for future optional parameters
}

// EndpointsClientGetBaseModelLogOptions contains the optional parameters for the EndpointsClient.GetBaseModelLog method.
type EndpointsClientGetBaseModelLogOptions struct {
// The duration in seconds that an SAS url should be valid. The default duration is 12 hours. When using BYOS
// (https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-encryption-of-data-at-rest#bring-your-own-storage-byos-for-customization-and-logging):
// A value of 0 means that a plain
// blob URI without SAS token will be generated.
	SasValidityInSeconds *int32
}

// EndpointsClientGetLogOptions contains the optional parameters for the EndpointsClient.GetLog method.
type EndpointsClientGetLogOptions struct {
// The duration in seconds that an SAS url should be valid. The default duration is 12 hours. When using BYOS
// (https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-encryption-of-data-at-rest#bring-your-own-storage-byos-for-customization-and-logging):
// A value of 0 means that a plain
// blob URI without SAS token will be generated.
	SasValidityInSeconds *int32
}

// EndpointsClientGetOptions contains the optional parameters for the EndpointsClient.Get method.
type EndpointsClientGetOptions struct {
	// placeholder for future optional parameters
}

// EndpointsClientListBaseModelLogsOptions contains the optional parameters for the EndpointsClient.NewListBaseModelLogsPager
// method.
type EndpointsClientListBaseModelLogsOptions struct {
// The duration in seconds that an SAS url should be valid. The default duration is 12 hours. When using BYOS
// (https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-encryption-of-data-at-rest#bring-your-own-storage-byos-for-customization-and-logging):
// A value of 0 means that a plain
// blob URI without SAS token will be generated.
	SasValidityInSeconds *int32

// Token to skip logs that were already retrieved in previous requests. Pagination starts from beginning when not defined.
	SkipToken *string

// Number of datasets that will be included after skipping.
	Top *int32
}

// EndpointsClientListLogsOptions contains the optional parameters for the EndpointsClient.NewListLogsPager method.
type EndpointsClientListLogsOptions struct {
// The duration in seconds that an SAS url should be valid. The default duration is 12 hours. When using BYOS
// (https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-encryption-of-data-at-rest#bring-your-own-storage-byos-for-customization-and-logging):
// A value of 0 means that a plain
// blob URI without SAS token will be generated.
	SasValidityInSeconds *int32

// Token to skip logs that were already retrieved in previous requests. Pagination starts from beginning when not defined.
	SkipToken *string

// Number of datasets that will be included after skipping.
	Top *int32
}

// EndpointsClientListOptions contains the optional parameters for the EndpointsClient.NewListPager method.
type EndpointsClientListOptions struct {
// A filtering expression for selecting a subset of the available endpoints. - Supported properties: displayName, description,
// createdDateTime, lastActionDateTime, status, locale. - Operators: - eq, ne
// are supported for all properties. - gt, ge, lt, le are supported for createdDateTime and lastActionDateTime. - and, or,
// not are supported. - Example: filter=locale eq 'en-US'
	Filter *string

// Number of datasets that will be skipped.
	Skip *int32

// Number of datasets that will be included after skipping.
	Top *int32
}

// EndpointsClientListSupportedLocalesOptions contains the optional parameters for the EndpointsClient.ListSupportedLocales
// method.
type EndpointsClientListSupportedLocalesOptions struct {
	// placeholder for future optional parameters
}

// EndpointsClientUpdateOptions contains the optional parameters for the EndpointsClient.Update method.
type EndpointsClientUpdateOptions struct {
	// placeholder for future optional parameters
}

// EvaluationsClientCreateOptions contains the optional parameters for the EvaluationsClient.Create method.
type EvaluationsClientCreateOptions struct {
	// placeholder for future optional parameters
}

// EvaluationsClientDeleteOptions contains the optional parameters for the EvaluationsClient.Delete method.
type EvaluationsClientDeleteOptions struct {
	// placeholder for future optional parameters
}

// EvaluationsClientGetFileOptions contains the optional parameters for the EvaluationsClient.GetFile method.
type EvaluationsClientGetFileOptions struct {
// The duration in seconds that an SAS url should be valid. The default duration is 12 hours. When using BYOS
// (https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-encryption-of-data-at-rest#bring-your-own-storage-byos-for-customization-and-logging):
// A value of 0 means that a plain
// blob URI without SAS token will be generated.
	SasValidityInSeconds *int32
}

// EvaluationsClientGetOptions contains the optional parameters for the EvaluationsClient.Get method.
type EvaluationsClientGetOptions struct {
	// placeholder for future optional parameters
}

// EvaluationsClientListFilesOptions contains the optional parameters for the EvaluationsClient.NewListFilesPager method.
type EvaluationsClientListFilesOptions struct {
// A filtering expression for selecting a subset of the available files. - Supported properties: name, createdDateTime, kind.
// - Operators: - eq, ne are supported for all properties. - gt, ge, lt, le are
// supported for createdDateTime. - and, or, not are supported. - Example: filter=name eq 'myaudio.wav' and kind eq 'Audio'
	Filter *string

// The duration in seconds that an SAS url should be valid. The default duration is 12 hours. When using BYOS
// (https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-encryption-of-data-at-rest#bring-your-own-storage-byos-for-customization-and-logging):
// A value of 0 means that a plain
// blob URI without SAS token will be generated.
	SasValidityInSeconds *int32

// Number of datasets that will be skipped.
	Skip *int32

// Number of datasets that will be included after skipping.
	Top *int32
}

// EvaluationsClientListOptions contains the optional parameters for the EvaluationsClient.NewListPager method.
type EvaluationsClientListOptions struct {
// A filtering expression for selecting a subset of the available evaluations. - Supported properties: displayName, description,
// createdDateTime, lastActionDateTime, status and locale. - Operators: - eq,
// ne are supported for all properties. - gt, ge, lt, le are supported for createdDateTime and lastActionDateTime. - and,
// or, not are supported. - Example: filter=displayName eq 'My evaluation'
	Filter *string

// Number of datasets that will be skipped.
	Skip *int32

// Number of datasets that will be included after skipping.
	Top *int32
}

// EvaluationsClientListSupportedLocalesOptions contains the optional parameters for the EvaluationsClient.ListSupportedLocales
// method.
type EvaluationsClientListSupportedLocalesOptions struct {
	// placeholder for future optional parameters
}

// EvaluationsClientUpdateOptions contains the optional parameters for the EvaluationsClient.Update method.
type EvaluationsClientUpdateOptions struct {
	// placeholder for future optional parameters
}

// ModelsClientAuthorizeCopyOptions contains the optional parameters for the ModelsClient.AuthorizeCopy method.
type ModelsClientAuthorizeCopyOptions struct {
	// placeholder for future optional parameters
}

// ModelsClientBeginCopyOptions contains the optional parameters for the ModelsClient.BeginCopy method.
type ModelsClientBeginCopyOptions struct {
// Resumes the long-running operation from the provided token.
	ResumeToken string
}

// ModelsClientCreateOptions contains the optional parameters for the ModelsClient.Create method.
type ModelsClientCreateOptions struct {
	// placeholder for future optional parameters
}

// ModelsClientDeleteOptions contains the optional parameters for the ModelsClient.Delete method.
type ModelsClientDeleteOptions struct {
	// placeholder for future optional parameters
}

// ModelsClientGetBaseModelManifestOptions contains the optional parameters for the ModelsClient.GetBaseModelManifest method.
type ModelsClientGetBaseModelManifestOptions struct {
// The duration in seconds that an SAS url should be valid. The default duration is 12 hours. When using BYOS
// (https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-encryption-of-data-at-rest#bring-your-own-storage-byos-for-customization-and-logging):
// A value of 0 means that a plain
// blob URI without SAS token will be generated.
	SasValidityInSeconds *int32
}

// ModelsClientGetBaseModelOptions contains the optional parameters for the ModelsClient.GetBaseModel method.
type ModelsClientGetBaseModelOptions struct {
	// placeholder for future optional parameters
}

// ModelsClientGetCustomModelManifestOptions contains the optional parameters for the ModelsClient.GetCustomModelManifest
// method.
type ModelsClientGetCustomModelManifestOptions struct {
// The duration in seconds that an SAS url should be valid. The default duration is 12 hours. When using BYOS
// (https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-encryption-of-data-at-rest#bring-your-own-storage-byos-for-customization-and-logging):
// A value of 0 means that a plain
// blob URI without SAS token will be generated.
	SasValidityInSeconds *int32
}

// ModelsClientGetCustomModelOptions contains the optional parameters for the ModelsClient.GetCustomModel method.
type ModelsClientGetCustomModelOptions struct {
	// placeholder for future optional parameters
}

// ModelsClientGetFileOptions contains the optional parameters for the ModelsClient.GetFile method.
type ModelsClientGetFileOptions struct {
// The duration in seconds that an SAS url should be valid. The default duration is 12 hours. When using BYOS
// (https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-encryption-of-data-at-rest#bring-your-own-storage-byos-for-customization-and-logging):
// A value of 0 means that a plain
// blob URI without SAS token will be generated.
	SasValidityInSeconds *int32
}

// ModelsClientListBaseModelsOptions contains the optional parameters for the ModelsClient.NewListBaseModelsPager method.
type ModelsClientListBaseModelsOptions struct {
// A filtering expression for selecting a subset of the available base models. - Supported properties: displayName, description,
// createdDateTime, lastActionDateTime, status, locale. - Operators: - eq, ne
// are supported for all properties. - gt, ge, lt, le are supported for createdDateTime and lastActionDateTime. - and, or,
// not are supported. - Example: filter=status eq 'NotStarted' or status eq
// 'Running'
	Filter *string

// Number of datasets that will be skipped.
	Skip *int32

// Number of datasets that will be included after skipping.
	Top *int32
}

// ModelsClientListCustomModelsOptions contains the optional parameters for the ModelsClient.NewListCustomModelsPager method.
type ModelsClientListCustomModelsOptions struct {
// A filtering expression for selecting a subset of the available models. - Supported properties: displayName, description,
// createdDateTime, lastActionDateTime, status, locale. - Operators: - eq, ne are
// supported for all properties. - gt, ge, lt, le are supported for createdDateTime and lastActionDateTime. - and, or, not
// are supported. - Example: filter=status eq 'NotStarted' or status eq 'Running'
	Filter *string

// Number of datasets that will be skipped.
	Skip *int32

// Number of datasets that will be included after skipping.
	Top *int32
}

// ModelsClientListFilesOptions contains the optional parameters for the ModelsClient.NewListFilesPager method.
type ModelsClientListFilesOptions struct {
// A filtering expression for selecting a subset of the available files. - Supported properties: name, createdDateTime, kind.
// - Operators: - eq, ne are supported for all properties. - gt, ge, lt, le are
// supported for createdDateTime. - and, or, not are supported. - Example: filter=name eq 'myaudio.wav' and kind eq 'Audio'
	Filter *string

// The duration in seconds that an SAS url should be valid. The default duration is 12 hours. When using BYOS
// (https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-encryption-of-data-at-rest#bring-your-own-storage-byos-for-customization-and-logging):
// A value of 0 means that a plain
// blob URI without SAS token will be generated.
	SasValidityInSeconds *int32

// Number of datasets that will be skipped.
	Skip *int32

// Number of datasets that will be included after skipping.
	Top *int32
}

// ModelsClientListSupportedLocalesOptions contains the optional parameters for the ModelsClient.ListSupportedLocales method.
type ModelsClientListSupportedLocalesOptions struct {
	// placeholder for future optional parameters
}

// ModelsClientUpdateOptions contains the optional parameters for the ModelsClient.Update method.
type ModelsClientUpdateOptions struct {
	// placeholder for future optional parameters
}

// OperationsClientGetModelCopyOptions contains the optional parameters for the OperationsClient.GetModelCopy method.
type OperationsClientGetModelCopyOptions struct {
	// placeholder for future optional parameters
}

// ProjectsClientCreateOptions contains the optional parameters for the ProjectsClient.Create method.
type ProjectsClientCreateOptions struct {
	// placeholder for future optional parameters
}

// ProjectsClientDeleteOptions contains the optional parameters for the ProjectsClient.Delete method.
type ProjectsClientDeleteOptions struct {
	// placeholder for future optional parameters
}

// ProjectsClientGetOptions contains the optional parameters for the ProjectsClient.Get method.
type ProjectsClientGetOptions struct {
	// placeholder for future optional parameters
}

// ProjectsClientListDatasetsOptions contains the optional parameters for the ProjectsClient.NewListDatasetsPager method.
type ProjectsClientListDatasetsOptions struct {
// A filtering expression for selecting a subset of the available datasets. - Supported properties: displayName, description,
// createdDateTime, lastActionDateTime, status, locale, kind. - Operators: - eq,
// ne are supported for all properties. - gt, ge, lt, le are supported for createdDateTime and lastActionDateTime. - and,
// or, not are supported. - Example: filter=createdDateTime gt 2022-02-01T11:00:00Z
	Filter *string

// Number of datasets that will be skipped.
	Skip *int32

// Number of datasets that will be included after skipping.
	Top *int32
}

// ProjectsClientListEndpointsOptions contains the optional parameters for the ProjectsClient.NewListEndpointsPager method.
type ProjectsClientListEndpointsOptions struct {
// A filtering expression for selecting a subset of the available endpoints. - Supported properties: displayName, description,
// createdDateTime, lastActionDateTime, status, locale. - Operators: - eq, ne
// are supported for all properties. - gt, ge, lt, le are supported for createdDateTime and lastActionDateTime. - and, or,
// not are supported. - Example: filter=locale eq 'en-US'
	Filter *string

// Number of datasets that will be skipped.
	Skip *int32

// Number of datasets that will be included after skipping.
	Top *int32
}

// ProjectsClientListEvaluationsOptions contains the optional parameters for the ProjectsClient.NewListEvaluationsPager method.
type ProjectsClientListEvaluationsOptions struct {
// A filtering expression for selecting a subset of the available evaluations. - Supported properties: displayName, description,
// createdDateTime, lastActionDateTime, status and locale. - Operators: - eq,
// ne are supported for all properties. - gt, ge, lt, le are supported for createdDateTime and lastActionDateTime. - and,
// or, not are supported. - Example filter=displayName eq 'My evaluation'
	Filter *string

// Number of datasets that will be skipped.
	Skip *int32

// Number of datasets that will be included after skipping.
	Top *int32
}

// ProjectsClientListModelsOptions contains the optional parameters for the ProjectsClient.NewListModelsPager method.
type ProjectsClientListModelsOptions struct {
// A filtering expression for selecting a subset of the available models. - Supported properties: displayName, description,
// createdDateTime, lastActionDateTime, status, locale. - Operators: - eq, ne are
// supported for all properties. - gt, ge, lt, le are supported for createdDateTime and lastActionDateTime. - and, or, not
// are supported. - Example: filter=status eq 'NotStarted' or status eq 'Running'
	Filter *string

// Number of datasets that will be skipped.
	Skip *int32

// Number of datasets that will be included after skipping.
	Top *int32
}

// ProjectsClientListOptions contains the optional parameters for the ProjectsClient.NewListPager method.
type ProjectsClientListOptions struct {
// A filtering expression for selecting a subset of the available projects. - Supported properties: displayName, description,
// createdDateTime, locale. - Operators: - eq, ne are supported for all
// properties. - gt, ge, lt, le are supported for createdDateTime. - and, or, not are supported. - Example: filter=displayName
// eq 'My test'
	Filter *string

// Number of datasets that will be skipped.
	Skip *int32

// Number of datasets that will be included after skipping.
	Top *int32
}

// ProjectsClientListSupportedLocalesOptions contains the optional parameters for the ProjectsClient.ListSupportedLocales
// method.
type ProjectsClientListSupportedLocalesOptions struct {
	// placeholder for future optional parameters
}

// ProjectsClientListTranscriptionsOptions contains the optional parameters for the ProjectsClient.NewListTranscriptionsPager
// method.
type ProjectsClientListTranscriptionsOptions struct {
// A filtering expression for selecting a subset of the available transcriptions. - Supported properties: displayName, description,
// createdDateTime, lastActionDateTime, status, locale. - Operators: - eq,
// ne are supported for all properties. - gt, ge, lt, le are supported for createdDateTime and lastActionDateTime. - and,
// or, not are supported. - Example: filter=createdDateTime gt 2022-02-01T11:00:00Z
	Filter *string

// Number of datasets that will be skipped.
	Skip *int32

// Number of datasets that will be included after skipping.
	Top *int32
}

// ProjectsClientUpdateOptions contains the optional parameters for the ProjectsClient.Update method.
type ProjectsClientUpdateOptions struct {
	// placeholder for future optional parameters
}

// TranscriptionsClientCreateOptions contains the optional parameters for the TranscriptionsClient.Create method.
type TranscriptionsClientCreateOptions struct {
	// placeholder for future optional parameters
}

// TranscriptionsClientDeleteOptions contains the optional parameters for the TranscriptionsClient.Delete method.
type TranscriptionsClientDeleteOptions struct {
	// placeholder for future optional parameters
}

// TranscriptionsClientGetFileOptions contains the optional parameters for the TranscriptionsClient.GetFile method.
type TranscriptionsClientGetFileOptions struct {
// The duration in seconds that an SAS url should be valid. The default duration is 12 hours. When using BYOS
// (https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-encryption-of-data-at-rest#bring-your-own-storage-byos-for-customization-and-logging):
// A value of 0 means that a plain
// blob URI without SAS token will be generated.
	SasValidityInSeconds *int32
}

// TranscriptionsClientGetOptions contains the optional parameters for the TranscriptionsClient.Get method.
type TranscriptionsClientGetOptions struct {
	// placeholder for future optional parameters
}

// TranscriptionsClientListFilesOptions contains the optional parameters for the TranscriptionsClient.NewListFilesPager method.
type TranscriptionsClientListFilesOptions struct {
// A filtering expression for selecting a subset of the available files. - Supported properties: name, createdDateTime, kind.
// - Operators: - eq, ne are supported for all properties. - gt, ge, lt, le are
// supported for createdDateTime. - and, or, not are supported. - Example: filter=name eq 'myaudio.wav.json' and kind eq 'Transcription'
	Filter *string

// The duration in seconds that an SAS url should be valid. The default duration is 12 hours. When using BYOS
// (https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-encryption-of-data-at-rest#bring-your-own-storage-byos-for-customization-and-logging):
// A value of 0 means that a plain
// blob URI without SAS token will be generated.
	SasValidityInSeconds *int32

// Number of datasets that will be skipped.
	Skip *int32

// Number of datasets that will be included after skipping.
	Top *int32
}

// TranscriptionsClientListOptions contains the optional parameters for the TranscriptionsClient.NewListPager method.
type TranscriptionsClientListOptions struct {
// A filtering expression for selecting a subset of the available transcriptions. - Supported properties: displayName, description,
// createdDateTime, lastActionDateTime, status, locale. - Operators: - eq,
// ne are supported for all properties. - gt, ge, lt, le are supported for createdDateTime and lastActionDateTime. - and,
// or, not are supported. - Example: filter=createdDateTime gt 2022-02-01T11:00:00Z
	Filter *string

// Number of datasets that will be skipped.
	Skip *int32

// Number of datasets that will be included after skipping.
	Top *int32
}

// TranscriptionsClientListSupportedLocalesOptions contains the optional parameters for the TranscriptionsClient.ListSupportedLocales
// method.
type TranscriptionsClientListSupportedLocalesOptions struct {
	// placeholder for future optional parameters
}

// TranscriptionsClientUpdateOptions contains the optional parameters for the TranscriptionsClient.Update method.
type TranscriptionsClientUpdateOptions struct {
	// placeholder for future optional parameters
}

// WebHooksClientCreateOptions contains the optional parameters for the WebHooksClient.Create method.
type WebHooksClientCreateOptions struct {
	// placeholder for future optional parameters
}

// WebHooksClientDeleteOptions contains the optional parameters for the WebHooksClient.Delete method.
type WebHooksClientDeleteOptions struct {
	// placeholder for future optional parameters
}

// WebHooksClientGetOptions contains the optional parameters for the WebHooksClient.Get method.
type WebHooksClientGetOptions struct {
	// placeholder for future optional parameters
}

// WebHooksClientListOptions contains the optional parameters for the WebHooksClient.NewListPager method.
type WebHooksClientListOptions struct {
// A filtering expression for selecting a subset of the available hooks. Supported properties: displayName, description, createdDateTime,
// lastActionDateTime, status and webUrl. - Operators: - eq, ne are
// supported for all properties. - gt, ge, lt, le are supported for createdDateTime and lastActionDateTime. - and, or, not
// are supported. - Example: filter=displayName eq 'test'
	Filter *string

// Number of datasets that will be skipped.
	Skip *int32

// Number of datasets that will be included after skipping.
	Top *int32
}

// WebHooksClientPingOptions contains the optional parameters for the WebHooksClient.Ping method.
type WebHooksClientPingOptions struct {
	// placeholder for future optional parameters
}

// WebHooksClientTestOptions contains the optional parameters for the WebHooksClient.Test method.
type WebHooksClientTestOptions struct {
	// placeholder for future optional parameters
}

// WebHooksClientUpdateOptions contains the optional parameters for the WebHooksClient.Update method.
type WebHooksClientUpdateOptions struct {
	// placeholder for future optional parameters
}

