// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.4, generator: @autorest/go@4.0.0-preview.70)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// Code generated by @autorest/go. DO NOT EDIT.

package speechclient

// DatasetsClientCommitBlocksResponse contains the response from method DatasetsClient.CommitBlocks.
type DatasetsClientCommitBlocksResponse struct {
	// placeholder for future response values
}

// DatasetsClientCreateResponse contains the response from method DatasetsClient.Create.
type DatasetsClientCreateResponse struct {
// Dataset
	Dataset

// Location contains the information returned from the Location header response.
	Location *string
}

// DatasetsClientDeleteResponse contains the response from method DatasetsClient.Delete.
type DatasetsClientDeleteResponse struct {
	// placeholder for future response values
}

// DatasetsClientGetBlocksResponse contains the response from method DatasetsClient.GetBlocks.
type DatasetsClientGetBlocksResponse struct {
// List of uploaded blocks.
	UploadedBlocks

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// DatasetsClientGetFileResponse contains the response from method DatasetsClient.GetFile.
type DatasetsClientGetFileResponse struct {
// File
	File
}

// DatasetsClientGetResponse contains the response from method DatasetsClient.Get.
type DatasetsClientGetResponse struct {
// Dataset
	Dataset

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// DatasetsClientListFilesResponse contains the response from method DatasetsClient.NewListFilesPager.
type DatasetsClientListFilesResponse struct {
// PaginatedFiles
	PaginatedFiles

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// DatasetsClientListResponse contains the response from method DatasetsClient.NewListPager.
type DatasetsClientListResponse struct {
// PaginatedDatasets
	PaginatedDatasets

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// DatasetsClientListSupportedLocalesResponse contains the response from method DatasetsClient.ListSupportedLocales.
type DatasetsClientListSupportedLocalesResponse struct {
// DatasetLocales
	Value map[string][]*DatasetKind
}

// DatasetsClientUpdateResponse contains the response from method DatasetsClient.Update.
type DatasetsClientUpdateResponse struct {
// Dataset
	Dataset

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// DatasetsClientUploadBlockResponse contains the response from method DatasetsClient.UploadBlock.
type DatasetsClientUploadBlockResponse struct {
	// placeholder for future response values
}

// DatasetsClientUploadResponse contains the response from method DatasetsClient.Upload.
type DatasetsClientUploadResponse struct {
// Dataset
	Dataset

// Location contains the information returned from the Location header response.
	Location *string
}

// EndpointsClientCreateResponse contains the response from method EndpointsClient.Create.
type EndpointsClientCreateResponse struct {
// Endpoint
	Endpoint

// Location contains the information returned from the Location header response.
	Location *string
}

// EndpointsClientDeleteBaseModelLogResponse contains the response from method EndpointsClient.DeleteBaseModelLog.
type EndpointsClientDeleteBaseModelLogResponse struct {
	// placeholder for future response values
}

// EndpointsClientDeleteBaseModelLogsResponse contains the response from method EndpointsClient.DeleteBaseModelLogs.
type EndpointsClientDeleteBaseModelLogsResponse struct {
	// placeholder for future response values
}

// EndpointsClientDeleteLogResponse contains the response from method EndpointsClient.DeleteLog.
type EndpointsClientDeleteLogResponse struct {
	// placeholder for future response values
}

// EndpointsClientDeleteLogsResponse contains the response from method EndpointsClient.DeleteLogs.
type EndpointsClientDeleteLogsResponse struct {
	// placeholder for future response values
}

// EndpointsClientDeleteResponse contains the response from method EndpointsClient.Delete.
type EndpointsClientDeleteResponse struct {
	// placeholder for future response values
}

// EndpointsClientGetBaseModelLogResponse contains the response from method EndpointsClient.GetBaseModelLog.
type EndpointsClientGetBaseModelLogResponse struct {
// File
	File
}

// EndpointsClientGetLogResponse contains the response from method EndpointsClient.GetLog.
type EndpointsClientGetLogResponse struct {
// File
	File
}

// EndpointsClientGetResponse contains the response from method EndpointsClient.Get.
type EndpointsClientGetResponse struct {
// Endpoint
	Endpoint

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// EndpointsClientListBaseModelLogsResponse contains the response from method EndpointsClient.NewListBaseModelLogsPager.
type EndpointsClientListBaseModelLogsResponse struct {
// PaginatedFiles
	PaginatedFiles
}

// EndpointsClientListLogsResponse contains the response from method EndpointsClient.NewListLogsPager.
type EndpointsClientListLogsResponse struct {
// PaginatedFiles
	PaginatedFiles

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// EndpointsClientListResponse contains the response from method EndpointsClient.NewListPager.
type EndpointsClientListResponse struct {
// PaginatedEndpoints
	PaginatedEndpoints

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// EndpointsClientListSupportedLocalesResponse contains the response from method EndpointsClient.ListSupportedLocales.
type EndpointsClientListSupportedLocalesResponse struct {
// Array of Get200ApplicationJsonItemsItem
	StringArray []*string
}

// EndpointsClientUpdateResponse contains the response from method EndpointsClient.Update.
type EndpointsClientUpdateResponse struct {
// Endpoint
	Endpoint

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// EvaluationsClientCreateResponse contains the response from method EvaluationsClient.Create.
type EvaluationsClientCreateResponse struct {
// Evaluation
	Evaluation

// Location contains the information returned from the Location header response.
	Location *string
}

// EvaluationsClientDeleteResponse contains the response from method EvaluationsClient.Delete.
type EvaluationsClientDeleteResponse struct {
	// placeholder for future response values
}

// EvaluationsClientGetFileResponse contains the response from method EvaluationsClient.GetFile.
type EvaluationsClientGetFileResponse struct {
// File
	File
}

// EvaluationsClientGetResponse contains the response from method EvaluationsClient.Get.
type EvaluationsClientGetResponse struct {
// Evaluation
	Evaluation

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// EvaluationsClientListFilesResponse contains the response from method EvaluationsClient.NewListFilesPager.
type EvaluationsClientListFilesResponse struct {
// PaginatedFiles
	PaginatedFiles

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// EvaluationsClientListResponse contains the response from method EvaluationsClient.NewListPager.
type EvaluationsClientListResponse struct {
// PaginatedEvaluations
	PaginatedEvaluations

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// EvaluationsClientListSupportedLocalesResponse contains the response from method EvaluationsClient.ListSupportedLocales.
type EvaluationsClientListSupportedLocalesResponse struct {
// Array of String
	StringArray []*string
}

// EvaluationsClientUpdateResponse contains the response from method EvaluationsClient.Update.
type EvaluationsClientUpdateResponse struct {
// Evaluation
	Evaluation

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// ModelsClientAuthorizeCopyResponse contains the response from method ModelsClient.AuthorizeCopy.
type ModelsClientAuthorizeCopyResponse struct {
// ModelCopyAuthorization
	ModelCopyAuthorization
}

// ModelsClientCopyResponse contains the response from method ModelsClient.BeginCopy.
type ModelsClientCopyResponse struct {
// Operation
	Operation
}

// ModelsClientCreateResponse contains the response from method ModelsClient.Create.
type ModelsClientCreateResponse struct {
// CustomModel
	CustomModel

// Location contains the information returned from the Location header response.
	Location *string
}

// ModelsClientDeleteResponse contains the response from method ModelsClient.Delete.
type ModelsClientDeleteResponse struct {
	// placeholder for future response values
}

// ModelsClientGetBaseModelManifestResponse contains the response from method ModelsClient.GetBaseModelManifest.
type ModelsClientGetBaseModelManifestResponse struct {
// ModelManifest
	ModelManifest
}

// ModelsClientGetBaseModelResponse contains the response from method ModelsClient.GetBaseModel.
type ModelsClientGetBaseModelResponse struct {
// BaseModel
	BaseModel
}

// ModelsClientGetCustomModelManifestResponse contains the response from method ModelsClient.GetCustomModelManifest.
type ModelsClientGetCustomModelManifestResponse struct {
// ModelManifest
	ModelManifest
}

// ModelsClientGetCustomModelResponse contains the response from method ModelsClient.GetCustomModel.
type ModelsClientGetCustomModelResponse struct {
// CustomModel
	CustomModel

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// ModelsClientGetFileResponse contains the response from method ModelsClient.GetFile.
type ModelsClientGetFileResponse struct {
// File
	File
}

// ModelsClientListBaseModelsResponse contains the response from method ModelsClient.NewListBaseModelsPager.
type ModelsClientListBaseModelsResponse struct {
// PaginatedBaseModels
	PaginatedBaseModels
}

// ModelsClientListCustomModelsResponse contains the response from method ModelsClient.NewListCustomModelsPager.
type ModelsClientListCustomModelsResponse struct {
// PaginatedCustomModels
	PaginatedCustomModels

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// ModelsClientListFilesResponse contains the response from method ModelsClient.NewListFilesPager.
type ModelsClientListFilesResponse struct {
// PaginatedFiles
	PaginatedFiles

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// ModelsClientListSupportedLocalesResponse contains the response from method ModelsClient.ListSupportedLocales.
type ModelsClientListSupportedLocalesResponse struct {
// Array of String
	StringArray []*string
}

// ModelsClientUpdateResponse contains the response from method ModelsClient.Update.
type ModelsClientUpdateResponse struct {
// CustomModel
	CustomModel

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// OperationsClientGetModelCopyResponse contains the response from method OperationsClient.GetModelCopy.
type OperationsClientGetModelCopyResponse struct {
// Operation
	Operation

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// ProjectsClientCreateResponse contains the response from method ProjectsClient.Create.
type ProjectsClientCreateResponse struct {
// Project
	Project

// Location contains the information returned from the Location header response.
	Location *string
}

// ProjectsClientDeleteResponse contains the response from method ProjectsClient.Delete.
type ProjectsClientDeleteResponse struct {
	// placeholder for future response values
}

// ProjectsClientGetResponse contains the response from method ProjectsClient.Get.
type ProjectsClientGetResponse struct {
// Project
	Project
}

// ProjectsClientListDatasetsResponse contains the response from method ProjectsClient.NewListDatasetsPager.
type ProjectsClientListDatasetsResponse struct {
// PaginatedDatasets
	PaginatedDatasets

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// ProjectsClientListEndpointsResponse contains the response from method ProjectsClient.NewListEndpointsPager.
type ProjectsClientListEndpointsResponse struct {
// PaginatedEndpoints
	PaginatedEndpoints

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// ProjectsClientListEvaluationsResponse contains the response from method ProjectsClient.NewListEvaluationsPager.
type ProjectsClientListEvaluationsResponse struct {
// PaginatedEvaluations
	PaginatedEvaluations

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// ProjectsClientListModelsResponse contains the response from method ProjectsClient.NewListModelsPager.
type ProjectsClientListModelsResponse struct {
// PaginatedCustomModels
	PaginatedCustomModels

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// ProjectsClientListResponse contains the response from method ProjectsClient.NewListPager.
type ProjectsClientListResponse struct {
// PaginatedProjects
	PaginatedProjects
}

// ProjectsClientListSupportedLocalesResponse contains the response from method ProjectsClient.ListSupportedLocales.
type ProjectsClientListSupportedLocalesResponse struct {
// Array of String
	StringArray []*string
}

// ProjectsClientListTranscriptionsResponse contains the response from method ProjectsClient.NewListTranscriptionsPager.
type ProjectsClientListTranscriptionsResponse struct {
// PaginatedTranscriptions
	PaginatedTranscriptions

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// ProjectsClientUpdateResponse contains the response from method ProjectsClient.Update.
type ProjectsClientUpdateResponse struct {
// Project
	Project
}

// TranscriptionsClientCreateResponse contains the response from method TranscriptionsClient.Create.
type TranscriptionsClientCreateResponse struct {
// Transcription
	Transcription

// Location contains the information returned from the Location header response.
	Location *string
}

// TranscriptionsClientDeleteResponse contains the response from method TranscriptionsClient.Delete.
type TranscriptionsClientDeleteResponse struct {
	// placeholder for future response values
}

// TranscriptionsClientGetFileResponse contains the response from method TranscriptionsClient.GetFile.
type TranscriptionsClientGetFileResponse struct {
// File
	File
}

// TranscriptionsClientGetResponse contains the response from method TranscriptionsClient.Get.
type TranscriptionsClientGetResponse struct {
// Transcription
	Transcription

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// TranscriptionsClientListFilesResponse contains the response from method TranscriptionsClient.NewListFilesPager.
type TranscriptionsClientListFilesResponse struct {
// PaginatedFiles
	PaginatedFiles

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// TranscriptionsClientListResponse contains the response from method TranscriptionsClient.NewListPager.
type TranscriptionsClientListResponse struct {
// PaginatedTranscriptions
	PaginatedTranscriptions

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// TranscriptionsClientListSupportedLocalesResponse contains the response from method TranscriptionsClient.ListSupportedLocales.
type TranscriptionsClientListSupportedLocalesResponse struct {
// Array of String
	StringArray []*string
}

// TranscriptionsClientUpdateResponse contains the response from method TranscriptionsClient.Update.
type TranscriptionsClientUpdateResponse struct {
// Transcription
	Transcription

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// WebHooksClientCreateResponse contains the response from method WebHooksClient.Create.
type WebHooksClientCreateResponse struct {
// WebHook
	WebHook

// Location contains the information returned from the Location header response.
	Location *string
}

// WebHooksClientDeleteResponse contains the response from method WebHooksClient.Delete.
type WebHooksClientDeleteResponse struct {
	// placeholder for future response values
}

// WebHooksClientGetResponse contains the response from method WebHooksClient.Get.
type WebHooksClientGetResponse struct {
// WebHook
	WebHook

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// WebHooksClientListResponse contains the response from method WebHooksClient.NewListPager.
type WebHooksClientListResponse struct {
// PaginatedWebHooks
	PaginatedWebHooks

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// WebHooksClientPingResponse contains the response from method WebHooksClient.Ping.
type WebHooksClientPingResponse struct {
// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// WebHooksClientTestResponse contains the response from method WebHooksClient.Test.
type WebHooksClientTestResponse struct {
// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

// WebHooksClientUpdateResponse contains the response from method WebHooksClient.Update.
type WebHooksClientUpdateResponse struct {
// WebHook
	WebHook

// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32
}

