// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.4, generator: @autorest/go@4.0.0-preview.70)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// Code generated by @autorest/go. DO NOT EDIT.

package translatortext

type Enum1 string

const (
	Enum1HTML Enum1 = "html"
	Enum1Plain Enum1 = "plain"
)

// PossibleEnum1Values returns the possible values for the Enum1 const type.
func PossibleEnum1Values() []Enum1 {
	return []Enum1{	
		Enum1HTML,
		Enum1Plain,
	}
}

type Enum2 string

const (
	Enum2Deleted Enum2 = "Deleted"
	Enum2Marked Enum2 = "Marked"
	Enum2NoAction Enum2 = "NoAction"
)

// PossibleEnum2Values returns the possible values for the Enum2 const type.
func PossibleEnum2Values() []Enum2 {
	return []Enum2{	
		Enum2Deleted,
		Enum2Marked,
		Enum2NoAction,
	}
}

type Get1ItemsItem string

const (
	Get1ItemsItemDictionary Get1ItemsItem = "dictionary"
	Get1ItemsItemTranslation Get1ItemsItem = "translation"
	Get1ItemsItemTransliteration Get1ItemsItem = "transliteration"
)

// PossibleGet1ItemsItemValues returns the possible values for the Get1ItemsItem const type.
func PossibleGet1ItemsItemValues() []Get1ItemsItem {
	return []Get1ItemsItem{	
		Get1ItemsItemDictionary,
		Get1ItemsItemTranslation,
		Get1ItemsItemTransliteration,
	}
}

