// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.4, generator: @autorest/go@4.0.0-preview.70)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// Code generated by @autorest/go. DO NOT EDIT.

package translatortext

type BreakSentenceResultItem struct {
	SentLen []*int32
}

// BreakSentenceTextInput - Text needed for break sentence request
type BreakSentenceTextInput struct {
	Text *string
}

type DetectResultItem struct {
	Text *string
}

// DetectTextInput - Text needed for detect request
type DetectTextInput struct {
	Text *string
}

type DictionaryExampleResultItem struct {
	Examples []*DictionaryExampleResultPropertiesItemsItem
	NormalizedSource *string
	NormalizedTarget *string
}

type DictionaryExampleResultPropertiesItemsItem struct {
	SourcePrefix *string
	SourceSuffix *string
	SourceTerm *string
	TargetPrefix *string
	TargetSuffix *string
	TargetTerm *string
}

// DictionaryExampleTextInput - Text needed for a dictionary example request
type DictionaryExampleTextInput struct {
	Text *string
	Translation *string
}

type DictionaryLookupResultItem struct {
	DisplaySource *string
	NormalizedSource *string
	Translations []*DictionaryLookupResultPropertiesItemsItem
}

type DictionaryLookupResultPropertiesItemsBackTranslationsItem struct {
	DisplayText *string
	FrequencyCount *int32
	NormalizedText *string
	NumExamples *int32
}

type DictionaryLookupResultPropertiesItemsItem struct {
	BackTranslations []*DictionaryLookupResultPropertiesItemsBackTranslationsItem
	Confidence *float32
	DisplayTarget *string
	NormalizedTarget *string
	PosTag *string
	PrefixWord *string
}

// DictionaryLookupTextInput - Text needed for a dictionary lookup request
type DictionaryLookupTextInput struct {
	Text *string
}

type ErrorMessage struct {
	Error *ErrorMessageError
}

type ErrorMessageError struct {
	Code *string
	Message *string
}

// LanguagesResult - Example of a successful languages request
type LanguagesResult struct {
	Dictionary *LanguagesResultDictionary
	Translation *LanguagesResultTranslation
	Transliteration *LanguagesResultTransliteration
}

type LanguagesResultDictionary struct {
	LanguageCode *LanguagesResultDictionaryLanguageCode
}

type LanguagesResultDictionaryLanguageCode struct {
	Dir *string
	Name *string
	NativeName *string
	Translations []*LanguagesResultDictionaryLanguageCodeTranslationsItem
}

type LanguagesResultDictionaryLanguageCodeTranslationsItem struct {
	Code *string
	Dir *string
	Name *string
	NativeName *string
}

type LanguagesResultTranslation struct {
	LanguageCode *LanguagesResultTranslationLanguageCode
}

type LanguagesResultTranslationLanguageCode struct {
	Dir *string
	Name *string
	NativeName *string
}

type LanguagesResultTransliteration struct {
	LanguageCode *LanguagesResultTransliterationLanguageCode
}

type LanguagesResultTransliterationLanguageCode struct {
	Name *string
	NativeName *string
	Scripts []*LanguagesResultTransliterationLanguageCodeScriptsItem
}

type LanguagesResultTransliterationLanguageCodeScriptsItem struct {
	Code *string
	Dir *string
	Name *string
	NativeName *string
	ToScripts []*LanguagesResultTransliterationLanguageCodeScriptsPropertiesItemsItem
}

type LanguagesResultTransliterationLanguageCodeScriptsPropertiesItemsItem struct {
	Code *string
	Dir *string
	Name *string
	NativeName *string
}

type TranslateResultAllItem struct {
	DetectedLanguage *TranslateResultAllItemDetectedLanguage
	Translations []*TranslateResultAllPropertiesItemsItem
}

type TranslateResultAllItemDetectedLanguage struct {
	Language *string
	Score *float64
}

type TranslateResultAllItemTranslationsItemAlignment struct {
	Proj *string
}

type TranslateResultAllItemTranslationsItemSentLen struct {
	SrcSentLen []*TranslateResultAllPropertiesItemsSentLenSrcSentLenItem
	TransSentLen []*TranslateResultAllPropertiesItemsSentLenTransSentLenItem
}

type TranslateResultAllItemTranslationsItemTransliteration struct {
	Script *string
	Text *string
}

type TranslateResultAllPropertiesItemsItem struct {
	Alignment *TranslateResultAllItemTranslationsItemAlignment
	SentLen *TranslateResultAllItemTranslationsItemSentLen
	Text *string
	To *string
	Transliteration *TranslateResultAllItemTranslationsItemTransliteration
}

type TranslateResultAllPropertiesItemsSentLenSrcSentLenItem struct {
	Integer *int32
}

type TranslateResultAllPropertiesItemsSentLenTransSentLenItem struct {
	Integer *int32
}

type TranslateResultItem struct {
	Translation []*TranslateResultPropertiesItemsItem
}

type TranslateResultPropertiesItemsItem struct {
	Text *string
	To *string
}

// TranslateTextInput - Text needed for a translate request
type TranslateTextInput struct {
	Text *string
}

type TransliterateResultItem struct {
	Script *string
	Text *string
}

// TransliterateTextInput - Text needed for a transliterate request
type TransliterateTextInput struct {
	Text *string
}

