// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.4, generator: @autorest/go@4.0.0-preview.70)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// Code generated by @autorest/go. DO NOT EDIT.

package translatortext

// TranslatorClientBreakSentenceResponse contains the response from method TranslatorClient.BreakSentence.
type TranslatorClientBreakSentenceResponse struct {
// Example of a successful break sentence request
	BreakSentenceResultItemArray []*BreakSentenceResultItem
}

// TranslatorClientDetectResponse contains the response from method TranslatorClient.Detect.
type TranslatorClientDetectResponse struct {
// Example of a successful detect request
	DetectResultItemArray []*DetectResultItem
}

// TranslatorClientDictionaryExamplesResponse contains the response from method TranslatorClient.DictionaryExamples.
type TranslatorClientDictionaryExamplesResponse struct {
// Example of a successful dictionary example request
	DictionaryExampleResultItemArray []*DictionaryExampleResultItem
}

// TranslatorClientDictionaryLookupResponse contains the response from method TranslatorClient.DictionaryLookup.
type TranslatorClientDictionaryLookupResponse struct {
// Example of a successful dictionary lookup request
	DictionaryLookupResultItemArray []*DictionaryLookupResultItem
}

// TranslatorClientLanguagesResponse contains the response from method TranslatorClient.Languages.
type TranslatorClientLanguagesResponse struct {
// Example of a successful languages request
	LanguagesResult
}

// TranslatorClientTranslateResponse contains the response from method TranslatorClient.Translate.
type TranslatorClientTranslateResponse struct {
// Example of a successful translate request, including all optional parameters.
	TranslateResultAllItemArray []*TranslateResultAllItem
}

// TranslatorClientTransliterateResponse contains the response from method TranslatorClient.Transliterate.
type TranslatorClientTransliterateResponse struct {
// Example of a successful transliterate request
	TransliterateResultItemArray []*TransliterateResultItem
}

